name: golangexampleoutyet

on: [push]

jobs:

    lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            stable: 'false'
            go-version: '1.14.1'
        - name: Lint
          run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
            golangci-lint run
            
    test:
        strategy:
            matrix:
                go version: [1.12.x, 1.13.x, 1.14.x]
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - name: install Go and checkout code
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}
            - uses: actions/checkout@v2
            - name: test
              run: |
                go test ./... -tags=unit -v -coverprofile cover.out
                go tool cover -func cover.out | grep total
                go tool cover -html=cover.out -o cover.html
    
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the repo
          uses: actions/checkout@v2
        - name: build and push to docker hub
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: cristinaespiritu/pocpublic
              tag_with_sha: true
